### ISSUE TITLE
suggestions don't suggest fortran syntax

### ISSUE THREAD

**Issue by ahelm** [hansec/vscode-fortran-ls#2]
First of, thank you for your plugin, it is really good and speedups coding in Fortran a lot. One issue I encountered is, suggestions based on the Fortran syntax are not shown, e.g. `if`, `endif` and so on. It would be great to have autocompletion for the Fortran syntax. Is this related with the language server or the other plugin which needs to be installed?

**Comment by hansec** [comment]
Thanks for the suggestion. This is actually a feature that would be added to the underlying [language server](https://github.com/hansec/fortran-language-server) not the VSCode extension. However, for cases like `if`, `do`, etc. the value would be in having a full snippet so the closing block is added at the same time. Some of these snippets are already provided by the [fortran extension](https://marketplace.visualstudio.com/items?itemName=Gimly81.fortran) that provides syntax highlighting. As for a more comprehensive integration into the language server I haven't quite decided how to best implement this, but I plan on it in the future (see [language server issue #47](https://github.com/hansec/fortran-language-server/issues/47)). I am going to close this issue since it is actually related to the upstream repo where there is now an open issue.
